version: '3.8'
services:
  book_co_web:
    image: node:18-alpine
    container_name: book_co_web
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "npm i && npm start"
    ports:
      - "3000:3000"